### ISSUE TITLE
Version not set for tags

### ISSUE THREAD

**Issue by fabaff** [Cyr-ius/heatzypy#7]
There seems to be an issue in the workflow as the version is not set properly. E.g., for [2.1.1](https://github.com/Cyr-ius/heatzypy/blob/2.1.1/setup.py#L35).

**Comment by Cyr-ius** [comment]
> There seems to be an issue in the workflow as the version is not set properly. E.g., for [2.1.1](https://github.com/Cyr-ius/heatzypy/blob/2.1.1/setup.py#L35).

This is normal because my github workflow replaces this keyword with the correct version at build time

**Comment by fabaff** [comment]
The `pyproject.toml` file which is part of the tarball of the latest release (https://github.com/cyr-ius/heatzypy/releases/tag/2.1.9) shows:

```bash
version     = "replace_by_workflow"
```
